version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install --upgrade 'six==1.15.0'
      -  pip install pre-commit cloudformation-cli-java-plugin
      -  pip install pyyaml --upgrade
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-codegurureviewer-repositoryassociation"
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-codegurureviewer-repositoryassociation/rpdk.log"
